#!/bin/sh
#
# Run update commands for everything we use on all platforms.
#
# Heuristics for ordering:
#
#   1. Update OS e.g. Ubuntu `do-release-upgrade`, macOS `softwareupdate`.
#
#   2. Update system packages e.g. Ubuntu `apt`, macOS `brew`.
#
#   3. Update tool packages: e.g. Node `npm`, Python`pip`.
#
#   4. Update repositories: `/opt`, `~/git`, etc.
#
# Guidance:
#
#   * Each script should be testing that it has what it needs to run.
#     This includes testing for any platform-specific needs.
#
#   * Each script should try to clean before running and after running.
#     This helps create disk space, and helps maintain dependencies.
#
# We welcome patches, pull requests, and ideas.
#
# Version: 4.2.1
# Created: 2015-06-01
# Updated: 2017-01-02
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf

## Update operating system
update-ubuntu-release
update-macos

## Update system packages
update-apt
update-brew
update-brew-cask
update-brewfile
update-mas
update-oh-my-zsh
update-yum

# Update tool packages
update-apm
update-gem
update-gemfile
update-pip
update-pod
update-podfile
update-npm
update-cabal
update-motion

# Update repositories
update-repos
