#!/bin/sh
#
# Run update commands for everything we use on all platforms.
#
# Heuristics:
#
#   1. Update OS and packages, such as `apt`, `softwareupdate`, `brew`, etc.
#   2. Update language application packages: `gem`, `pip`, `npm`, `motion`, etc.
#   3. Update our local git repositories: `/opt`, `~/git`, etc.
#
# More to come. We welcome patches, pull requests, and ideas.
#
# Version: 2.4
# Created: 2015-06-01
# Updated: 2016-01-17
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
update-apt
update-ubuntu-release
update-osx
update-brew
update-oh-my-zsh
update-apm
update-gem
update-pip
update-npm
update-cabal
update-motion
update-repos
